genre_map = {'Slice of Life': 0,
             'Psychological': 1,
             'Kids': 2,
             'Fantasy': 3,
             'Magic': 4,
             'Yuri': 5,
             'Police': 6,
             'Shoujo Ai': 7,
             'Historical': 8,
             'Mystery': 9,
             'Horror': 10,
             'Cars': 11,
             'Mecha': 12,
             'Demons': 13,
             'School': 14,
             'Military': 15,
             'Hentai': 16,
             'Drama': 17,
             'Thriller': 18,
             'Adventure': 19,
             'Seinen': 20,
             'Harem': 21,
             'Space': 22,
             'Supernatural': 23,
             'Sci-Fi': 24,
             'Shounen': 25,
             'Ecchi': 26,
             'Game': 27,
             'Shounen Ai': 28,
             'Yaoi': 29,
             'Parody': 30,
             'Action': 31,
             'Vampire': 32,
             'Comedy': 33,
             'Super Power': 34,
             'Martial Arts': 35,
             'Shoujo': 36,
             'Dementia': 37,
             'Music': 38,
             'Josei': 39,
             'Sports': 40,
             'Samurai': 41,
             'Romance': 42}
